---
title: "llm_classifier_results"
output: html_document
date: "2026-04-02"
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(readxl)


prereg_classified <- read_csv("prereg_classified.csv")

# add JEPLMC data
prereg_classified_JEPLMC <- read_csv("prereg_classified_JEPLMC.csv") %>% 
  select(-`Journal Title`)

# combine these into one df
prereg_classified <- bind_rows(prereg_classified, prereg_classified_JEPLMC)

data_key <- bind_rows(
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2020"),
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2021"),
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2022"),
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2023"),
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2024"),
  read_excel("PsycArticles/data_key (1).xlsx", sheet = "2025")
)

```

```{r}
prereg_classified <- left_join(prereg_classified,
                                 data_key %>% 
                                  select(DOI, `Journal Title`),
                                  by = "DOI") %>%  # add journal title to our dataset
                            rename(journal_title = `Journal Title`)

# Count the number of articles that use the OSF preregistration template for each journal (we need at least 20 per journal)
prereg_classified %>% 
  group_by(journal_title) %>% 
  filter(uses_osf_template == TRUE) %>% 
  summarise(n_articles = n_distinct(DOI)) %>% 
  ungroup()

# Save those that use the prereg template in a separate dataframe
prereg_template <- prereg_classified %>% 
  filter(uses_osf_template == TRUE)

```


```{r}
# Randomly sample 20 articles per journal
set.seed(28042026) # For reproducibility

sample <- prereg_template %>% 
  group_by(DOI) %>%
  slice_sample(n = 1) %>%  # first select one study per article 
  ungroup() %>%
  group_by(journal_title) %>%
  slice_sample(n = 20) %>%  # then sample 20 articles per journal
  select(c(DOI, reasoning, study_number, all_registration_urls, journal_title)) %>% 
  ungroup()
  

# Assign two coders to each article, ensure the same coder doesn't appear as both coder 1 and coder 2
n <- nrow(sample)
coders <- c("BC", "JC", "EK", "SaB", "SiB")

# Generate all possible pairs where coder_1 != coder_2
pairs <- expand.grid(coder_1 = coders, coder_2 = coders) %>%
  filter(coder_1 != coder_2)

# Repeat pairs to cover all rows and shuffle
pairs <- pairs[rep(seq_len(nrow(pairs)), length.out = nrow(sample)), ]
pairs <- pairs[sample(nrow(pairs)), ]

# Assign to sample
sample$coder_1 <- pairs$coder_1
sample$coder_2 <- pairs$coder_2


# Check balance
table(sample$coder_1)
table(sample$coder_2)

# Check if any coder was assigned to coder_1 and coder_2 for a single article
any(sample$coder_1 == sample$coder_2)
```

```{r}
# Add article number for our reference
sample <- sample %>% 
  mutate(article_number = row_number()) %>% 
  select(-reasoning)
```

```{r}
# Cleaning
sample <- sample %>% 
  mutate(doi_link = paste0("doi.org/", DOI))

sample <- sample %>% 
  select(article_number, DOI, doi_link, study_number, all_registration_urls, journal_title, coder_1, coder_2)

write_csv(sample, "coders_sheets/MASTER_sample")

# Create a sheet for each person
# set seed for when we randomise article order 
set.seed(28042026)

sample_BC <- sample %>% 
  filter(coder_1 == "BC" | coder_2 == "BC") %>% 
  select(-c(coder_1, coder_2))

sample_BC <- sample_BC %>% slice_sample(n = nrow(sample_BC))

write_csv(sample_BC, "coders_sheets/sample_BC.csv")

sample_JC <- sample %>% 
  filter(coder_1 == "JC" | coder_2 == "JC") %>% 
  select(-c(coder_1, coder_2))

sample_JC <- sample_JC %>% slice_sample(n = nrow(sample_JC))

write_csv(sample_JC, "coders_sheets/sample_JC.csv")

sample_SiB <- sample %>% 
  filter(coder_1 == "SiB" | coder_2 == "SiB") %>% 
  select(-c(coder_1, coder_2))

sample_SiB <- sample_SiB %>% slice_sample(n = nrow(sample_SiB))

write_csv(sample_SiB, "coders_sheets/sample_SiB.csv")

sample_SaB <- sample %>% 
  filter(coder_1 == "SaB" | coder_2 == "SaB") %>% 
  select(-c(coder_1, coder_2))

sample_SaB <- sample_SaB %>% slice_sample(n = nrow(sample_SaB))

write_csv(sample_SaB, "coders_sheets/sample_SaB.csv")

sample_EK <- sample %>% 
  filter(coder_1 == "EK" | coder_2 == "EK") %>% 
  select(-c(coder_1, coder_2))

sample_EK <- sample_EK %>% slice_sample(n = nrow(sample_EK))

write_csv(sample_EK, "coders_sheets/sample_EK.csv")
```

# Additions and changes
```{r}
# for 10.1037/xge0001295 LLM classifier did not extract studies. Randomly select a study from the list:

art_25_studies <- tibble(study = c("Experiment 1A", "Experiment 1B", "Experiment 2A", "Experiment 2B"))

set.seed(28042026) # For reproducibility

art_25_studies %>% 
  slice_sample(n = 1)

art_16_studies <- tibble(study = c("Study 1", "Experiment 2", "Experiment 3", "Preliminary Study"))

set.seed(28042026) # For reproducibility

art_16_studies %>% 
  slice_sample(n = 1)
```

```{r}
# Replace excluded articles
remaining_articles <- anti_join(prereg_template, sample, by = "DOI") 

set.seed(28042026)

jep_hpp_replace <- remaining_articles %>% 
  filter(journal_title == "Journal of Experimental Psychology: Human Perception and Performance") %>% 
  group_by(DOI) %>%
  slice_sample(n = 1) %>%  
  ungroup() %>%
  slice_sample(n = 2) %>%  
  select(c(DOI, reasoning, study_number, all_registration_urls, journal_title)) 

write.csv(jep_hpp_replace, "jep_hpp_replace.csv")

already_replaced <- remaining_articles |> 
  filter(DOI %in% c("10.1037/pspa0000309", "10.1037/pspp0000511", "10.1037/pspi0000325")) # something with the randomisation went wrong with the JPSP replacements, these three articles were already replaced earlier 

new_jpsp <- remaining_articles %>%
  filter(journal_title == "Journal of Personality and Social Psychology",
         !DOI %in% already_replaced) %>%
  group_by(DOI) %>% slice_sample(n = 1) %>% ungroup() %>%
  slice_sample(n = 1)

jpsp_replace <- bind_rows(already_replaced, new_jpsp) |> 
    select(c(DOI, reasoning, study_number, all_registration_urls, journal_title)) 

write.csv(jpsp_replace, "jpsp_replace.csv")

jep_lmc_replace <- remaining_articles %>% 
  filter(journal_title == "Journal of Experimental Psychology: Learning, Memory, and Cognition") %>% 
  group_by(DOI) %>%
  slice_sample(n = 1) %>%  
  ungroup() %>%
  slice_sample(n = 2) %>%  
  select(c(DOI, reasoning, study_number, all_registration_urls, journal_title)) 

write.csv(jep_lmc_replace, "jep_lmc_replace.csv")

emotion_replace <- remaining_articles %>% 
  filter(journal_title == "Emotion") %>% 
  group_by(DOI) %>%
  slice_sample(n = 1) %>%  
  ungroup() %>%
  slice_sample(n = 5) %>%  
  select(c(DOI, reasoning, study_number, all_registration_urls, journal_title)) 

write.csv(emotion_replace, "emotion_replace.csv")


```



