---
title: "Simulated Data RegCheck Validation Study"
output: html_document
date: "2025-12-21"
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(42) #set seed for reproducibility
```

```{r set up variables}
#Metadata

paper_ids <- 1:800 #n papers we sample

journals <- c(
  "Collabra",
  "JEP:G",
  "NHB",
  "PLOS",
  "Psych Science",
  "JPSP",    
  "Emotion",
  "JESP",
  "JRP",
  "PSPB",
  "Cognition",
  "JEP:HPP",
  "JEP:LMC",
  "JML",
  "MC"
) #abbreivated journal names


human_coders <- c("BC", "JC", "ME", "AA", "BB", "CC") #initials of human coders. Can add to this if we want > 6 coders

dimensions <- c(
  "Hypotheses",
  "Data source",
  "Inclusion and exclusion criteria",
  "Sample Size",
  "Manipulated Variables",
  "Measured variables",
  "Statistical models",
  "Transformations",
  "Missing data"
) 

# Variables coded:

# JC: Yes, I think it's fine that we just simulate cosine similarities separately without needing to literally simulate strings. It's also easier then for simulating specific relationships between variables by specifying the numeric cosine similarity values directly

random_text <- function(n, length = 50) { #a function that randomly generates a string of [length] letters, @Jamie: Ideally this would be randomly sampling words [less important] and some coders would extract more similar text than others [more important]. Currrently I'm avoiding that by simulating cosine_similarity totally independent of this, which is probably fine?
  replicate(
    n,
    paste(sample(letters, length, replace = TRUE), collapse = "")
  )
}

deviation_decision_levels <- c("deviation", "no deviation", "not enough information")

```

```{r build data}

# First, assing two coders to each paper, and expand each row by dimensions 
df <- do.call(
  rbind,
  lapply(paper_ids, function(pid) {
    
    # select 2 human coders per paper + RegCheck
    coders <- c(sample(human_coders, 2, replace = FALSE), "RegCheck")
    
    # expand to coder x dimension
    expand.grid(
      paper_id = pid,
      coder = coders,
      dimension = dimensions,
      stringsAsFactors = FALSE
    )
  })
)

# add journal
journal_df <- data.frame(
  paper_id = unique(df$paper_id),
  journal = sample(journals, length(unique(df$paper_id)), replace = TRUE)
)

df <- df %>%
  left_join(journal_df, by = "paper_id")

# add random text (this is supposed to be the text coders extracted for each dimension)
df$text <- random_text(nrow(df)) 
```


```{r coder agreement}
pair_agreement <- list(
  "BC_JC" = 0.85,
  "BC_ME" = 0.80,
  "BC_AA" = 0.65,
  "BC_BB" = 0.70,
  "JC_ME" = 0.90,
  "JC_AA" = 0.80,
  "JC_BB" = 0.75,
  "ME_AA" = 0.80,
  "ME_BB" = 0.75,
  "AA_BB" = 0.80,
  
  "BC_RegCheck" = 0.90,
  "JC_RegCheck" = 0.88,
  "ME_RegCheck" = 0.92,
  "AA_RegCheck" = 0.80,
  "BB_RegCheck" = 0.77
)

# Function that gets the probability that coders agree on the deviation decision
get_p_agree <- function(c1, c2, pair_agreement, default = 0.65) {
  key1 <- paste(c1, c2, sep = "_")
  key2 <- paste(c2, c1, sep = "_")
  pair_agreement[[key1]] %||%
    pair_agreement[[key2]] %||%
    default
}
```

```{r deviation decision}
df <- df %>%
  group_by(paper_id, dimension) %>%
  mutate(
    # choose reference coder (first human) and randomly select their decision
    reference_coder = coder[coder != "RegCheck"][1],
    reference_decision = sample(deviation_decision_levels, 1)
  ) %>%
  ungroup()

df <- df %>%
  rowwise() %>%
  mutate(
    deviation_decision = {
      if (coder == reference_coder) {
        reference_decision
      } else {
        p <- get_p_agree(
          coder,
          reference_coder,
          pair_agreement
        )
        
        if (runif(1) < p) { #p % of the time, the coders will agree. Otherwise, a different deviaiton decision will be randomly selected
          reference_decision
        } else {
          sample(
            setdiff(deviation_decision_levels, reference_decision),
            1
          )
        }
      }
    }
  ) %>%
  ungroup() %>%
  select(-reference_coder, -reference_decision) #remove referece coder and reference decision columns

# add deviation severity (I don't do anything with this; again, it's randomly sampled and doesn't account for the fact that coders' decisions will be correlated)
df_raw <- df %>% 
  mutate(severity = ifelse(deviation_decision == "deviation", 
                           sample(c("green", "orange", "red"), 
                                  size = n(), 
                                  replace = TRUE), 
                           NA))
```

To calculate cosine similarity, we need to make the rows pairwise comparisons 
```{r convert rows to be pairwise comparisons}
# To get pairwise comparisons, create one dataset with just the human coders, and one with regcheck x human coder
humans <- df_raw %>%
  filter(coder != "RegCheck")

regcheck <- df_raw %>%
  filter(coder == "RegCheck")

#human-to-human comparison
hh_pairs <- humans %>%
  group_by(paper_id, dimension) %>%
  summarise(
    coder_1 = coder[1],
    coder_2 = coder[2],
    decision_1 = deviation_decision[1],
    decision_2 = deviation_decision[2],
    journal = first(journal),
    .groups = "drop"
  ) %>%
  mutate(
    comparison_type = "human1_human2",
    agree = as.integer(decision_1 == decision_2) #,
    # cosine_similarity = rnorm(n(), mean = .77, sd = .02) fully randomised cosine_similarity - in code below, I've tried to add effects of: paper, coder pair, dimension, and journal (plus some random effect)
  )

#regcheck-to-human comparison
rh_pairs <- humans %>%
  inner_join(
    regcheck,
    by = c("paper_id", "dimension", "journal"),
    suffix = c("_human", "_reg")
  ) %>%
  mutate(
    coder_1 = "RegCheck",
    coder_2 = coder_human,
    comparison_type = ifelse(
      coder_human == first(coder_human),
      "regcheck_human1",
      "regcheck_human2"
    ),
    agree = as.integer(deviation_decision_human == deviation_decision_reg)#,
    #cosine_similarity = rnorm(n(), mean = .70, sd = .05)
  ) %>%
  select(
    coder_1,
    coder_2,
    comparison_type,
    journal,
    paper_id,
    dimension,
    #cosine_similarity,
    agree
  )

# Combine
pairwise_df <- bind_rows(
  hh_pairs %>%
    select(
      coder_1,
      coder_2,
      comparison_type,
      journal,
      paper_id,
      dimension,
      #cosine_similarity,
      agree
    ),
  rh_pairs
)

pairwise_df <- pairwise_df %>%
  mutate(coder_pair = paste(pmin(coder_1, coder_2), pmax(coder_1, coder_2), sep = "_"))
```

```{r add cosine similarity}
#@Jamie, this is my attempt at adding paper, coder pair, dimension, and journal effects for cosine similarity (I haven't done this for agreement)

# Set variance for effects (@Jamie, are these even realistic sds for cosine_similarity?)
sd_paper <- .009           # variability between papers
sd_coder_pair <- .008      # variability between coder pairs
sd_dimension <- .010       # variability between dimensions
sd_journal <- .002        # variability between journals
sd_residual <- .005        # residual / measurement error

# generate random effects 
# the only vector of grouping variables we don't have is coder_pairs, so lets create that
coder_pairs <- unique(pairwise_df$coder_pair)

# Now, let's give each unique grouping variable an effect
paper_effects <- rnorm(length(paper_ids), 0, sd_paper)
names(paper_effects) <- paper_ids

coder_pair_effects <- rnorm(length(coder_pairs), 0, sd_coder_pair)
names(coder_pair_effects) <- coder_pairs

dimension_effects <- rnorm(length(dimensions), 0, sd_dimension)
names(dimension_effects) <- dimensions

journal_effects <- rnorm(length(journals), 0, sd_journal)
names(journal_effects) <- journals

# set a base mean by comparison type (we can tinker with these)
base_mean <- c(
  "human1_human2" = .77,
  "regcheck_human1" = .70,
  "regcheck_human2" = .70
)

# simulate final cosine similarity
pairwise_df <- pairwise_df %>%
  rowwise() %>%
  mutate(
    cosine_similarity = base_mean[comparison_type] +
      paper_effects[as.character(paper_id)] +
      coder_pair_effects[as.character(coder_pair)] +
      dimension_effects[as.character(dimension)] +
      journal_effects[as.character(journal)] +
      rnorm(1, 0, sd_residual)
  ) %>%
  ungroup() %>% 
  mutate(cosine_similarity = pmin(pmax(cosine_similarity, 0), 1)) # this is currently not a problem because i set the sd for the grouping variable effects to be pretty small (and the mean for comparison types is not super high), but we don't want cosine_similarity to be able to be greater than one. This solution is not ideal. ChatGPT suggested pmin(), but I'm not sure if that changes the scale (@Jamie, any thoughts? Again, this is more of an issue if cosine_similarity in our simulation gets closer to 1) 
# JC: the change I added here should work
```


# Planned analyses
```{r load packages}
library(lme4)
library(emmeans)
```

# RQ1: Cosine similarity

```{r rq1 analyses}
rq1_model  <- lmer(cosine_similarity ~ comparison_type + (1 | journal) + (1 | paper_id) + (1 | dimension) + (1 | coder_pair), data = pairwise_df) #I added dimension and coder pair as random effects... I worry that too many random effects could result in singular fit issues but I'm not sure. We could plan to drop random effects where the model shows the random effect's variance to be 0? @Jamie, any thoughts?

summary(rq1_model) #view model output

emm1 <- emmeans(rq1_model, ~ comparison_type)

omnibus_contrast <- contrast(
  emm1,
  method = list("RC_avg_vs_HH" = c(-1, 0.5, 0.5))
) 

criterion <- 0.5*sd(pairwise_df$cosine_similarity[pairwise_df$comparison_type == "human1_human2"])

regcheck_avg_ci <- confint(omnibus_contrast)
lower_ci <- regcheck_avg_ci$asymp.LCL[1]

noninferior <- (lower_ci > -criterion)

noninferior  #FALSE means RCs agreement is lower than the criterion. TRUE means RCs agreement is at least as consistent as coders are with one another

#RQ1 by dimension (i.e., does the relationship between cosine similarity and comparison type vary by dimension?)
  #@Jamie, I wondered if this might be too many analyses to commit to, but I think we have to break it down by dimension (my preference would be to provide that information visually, like I had originally added to the prereg document, but we could also run the same significance test and report it in a table [or summarise the info in a plot and provide the tests in a table in a supplement]. Let me know if you have preferences on where to report this and/ or thoughts on the analysis below!)

rq1a_model  <- lmer(cosine_similarity ~ comparison_type*dimension + (1 | journal) + (1 | paper_id) + (1 | coder_pair)  , data = pairwise_df) #removed random effect for dimension, added the interaction

summary(rq1a_model)

emm1a <- emmeans(rq1a_model, ~ comparison_type | dimension)

dimension_contrasts <- contrast(
  emm1a,
  method = list("RC_avg_vs_HH" = c(-1, 0.5, 0.5))
) 

dimension_ci_holm <- summary( #Holm adjustment for multiple comparisons
  dimension_contrasts,
  infer = TRUE,
  adjust = "holm"
)

criterion_1a <- pairwise_df %>% 
  filter(comparison_type == "human1_human2") %>%
  group_by(dimension) %>% 
  summarise(
    criterion = -0.5 * sd(cosine_similarity),
    .groups = "drop"
  )

regcheck_dimension_ci <- dimension_ci_holm %>% 
  group_by(dimension) %>% 
  summarise(lower_ci = asymp.LCL)

noninferior_dimension <- left_join(criterion_1a, regcheck_dimension_ci, by = "dimension")

noninferior_dimension <- noninferior_dimension %>% 
  mutate(result = lower_ci > criterion)

view(noninferior_dimension) #FALSE means RCs agreement is lower than the criterion. TRUE means RCs agreement is at least as consistent as coders are with one another
  
```


## Jamie additions and simulation flow

```{r}

simulate_regcheck_validation_data <- function(
  # size / design
  n_papers = 800,
  human_coders = c("BC", "JC", "ME", "AA", "BB", "CC"),
  dimensions = c(
    "Hypotheses",
    "Data source",
    "Inclusion and exclusion criteria",
    "Sample Size",
    "Manipulated Variables",
    "Measured variables",
    "Statistical models",
    "Transformations",
    "Missing data"
  ),
  journals = c(
    "Collabra", "JEP:G", "NHB", "PLOS", "Psych Science", "JPSP",
    "Emotion", "JESP", "JRP", "PSPB", "Cognition", "JEP:HPP",
    "JEP:LMC", "JML", "MC"
  ),
  deviation_levels = c("deviation", "no deviation", "not enough information"),

  # scenario knobs (RQ2-ish: decision consistency)
  hh_agree_mean = 0.80,
  rc_agree_mean = 0.88,
  hh_agree_sd   = 0.00,   # add heterogeneity across HH pairs if desired
  rc_agree_sd   = 0.00,   # add heterogeneity across RC-H pairs if desired
  agreement_default = 0.65, # fallback if a pair is missing

  # scenario knobs (RQ1-ish: cosine similarity levels)
  cosine_base_mean = c(
    "human_human"     = 0.77,
    "regcheck_human"  = 0.70
  ),

  # random-effect SDs (fixed “variation” across simulations)
  re_sds = list(
    paper      = 0.009,
    coder_pair = 0.008,
    dimension  = 0.010,
    journal    = 0.002,
    residual   = 0.005
  ),

  # reuse realised random effects across runs (optional)
  random_effects = NULL,

  # optional: generate placeholder extracted text
  add_text = FALSE,
  text_length = 50
) {
  suppressPackageStartupMessages({
    library(dplyr)
    library(tidyr)
    library(purrr)
    library(stringr)
  })

  # ----------------------------
  # helpers
  # ----------------------------
  clamp01 <- function(x) pmin(pmax(x, 0), 1)

  random_text <- function(n, length = 50) {
    replicate(
      n,
      paste(sample(letters, length, replace = TRUE), collapse = "")
    )
  }

  # build a *coherent* pair-agreement lookup from scenario knobs
  make_pair_agreement <- function(human_coders, hh_mean, rc_mean, hh_sd, rc_sd) {
    # all unordered human-human pairs
    hh_pairs <- combn(human_coders, 2, simplify = FALSE)
    hh_vals <- map_dbl(hh_pairs, \(p) clamp01(rnorm(1, hh_mean, hh_sd)))
    names(hh_vals) <- map_chr(hh_pairs, \(p) paste0(p[1], "_", p[2]))

    # all human-RegCheck pairs
    rc_vals <- map_dbl(human_coders, \(h) clamp01(rnorm(1, rc_mean, rc_sd)))
    names(rc_vals) <- paste0(human_coders, "_RegCheck")

    as.list(c(hh_vals, rc_vals))
  }

  get_p_agree <- function(c1, c2, pair_agreement, default = 0.65) {
    key1 <- paste(c1, c2, sep = "_")
    key2 <- paste(c2, c1, sep = "_")
    pair_agreement[[key1]] %||%
      pair_agreement[[key2]] %||%
      default
  }

  # construct universe of coder pairs (for stable coder-pair REs across runs)
  all_possible_coder_pairs <- function(human_coders) {
    all_coders <- c(human_coders, "RegCheck")
    all_pairs <- combn(all_coders, 2, simplify = FALSE)
    map_chr(all_pairs, \(p) paste0(pmin(p[1], p[2]), "_", pmax(p[1], p[2])))
  }

  # ----------------------------
  # design
  # ----------------------------
  paper_ids <- seq_len(n_papers)

  # Long dataset: paper x (2 humans + RegCheck) x dimension
  df_long <- bind_rows(lapply(paper_ids, function(pid) {
    chosen_humans <- sample(human_coders, 2, replace = FALSE)
    coders <- c(chosen_humans, "RegCheck")
    expand_grid(
      paper_id = pid,
      coder = coders,
      dimension = dimensions
    )
  }))

  # Add journal per paper
  journal_df <- tibble(
    paper_id = paper_ids,
    journal = sample(journals, length(paper_ids), replace = TRUE)
  )
  df_long <- df_long %>% left_join(journal_df, by = "paper_id")

  if (isTRUE(add_text)) {
    df_long <- df_long %>% mutate(text = random_text(nrow(df_long), length = text_length))
  }

  # ----------------------------
  # decision simulation (bug-fixed)
  # ----------------------------
  pair_agreement <- make_pair_agreement(
    human_coders = human_coders,
    hh_mean = hh_agree_mean,
    rc_mean = rc_agree_mean,
    hh_sd = hh_agree_sd,
    rc_sd = rc_agree_sd
  )

  # BUG FIX: reference decision must be sampled ONCE per (paper_id, dimension)
  ref_tbl <- df_long %>%
    filter(coder != "RegCheck") %>%
    group_by(paper_id, dimension) %>%
    summarise(
      reference_coder = first(coder),
      reference_decision = sample(deviation_levels, 1),
      .groups = "drop"
    )

  df_long <- df_long %>%
    left_join(ref_tbl, by = c("paper_id", "dimension")) %>%
    rowwise() %>%
    mutate(
      deviation_decision = {
        if (coder == reference_coder) {
          reference_decision
        } else {
          p <- get_p_agree(coder, reference_coder, pair_agreement, default = agreement_default)
          if (runif(1) < p) {
            reference_decision
          } else {
            sample(setdiff(deviation_levels, reference_decision), 1)
          }
        }
      }
    ) %>%
    ungroup() %>%
    select(-reference_coder, -reference_decision)

  # Optional severity (still simplistic; correlated severity can be layered later)
  df_raw <- df_long %>%
    mutate(
      severity = if_else(
        deviation_decision == "deviation",
        sample(c("green", "orange", "red"), size = n(), replace = TRUE),
        NA_character_
      )
    )

  # ----------------------------
  # convert to pairwise rows
  # ----------------------------
  humans <- df_raw %>% filter(coder != "RegCheck")
  regcheck <- df_raw %>% filter(coder == "RegCheck")

  # HH: one row per paper x dimension (exactly 2 humans by construction)
  hh_pairs <- humans %>%
    group_by(paper_id, dimension) %>%
    summarise(
      coder_1 = coder[1],
      coder_2 = coder[2],
      decision_1 = deviation_decision[1],
      decision_2 = deviation_decision[2],
      journal = first(journal),
      .groups = "drop"
    ) %>%
    mutate(
      comparison_type = "human_human",
      agree = as.integer(decision_1 == decision_2)
    )

  # RC–H: one row per human per paper x dimension
  rh_pairs <- humans %>%
    inner_join(
      regcheck,
      by = c("paper_id", "dimension", "journal"),
      suffix = c("_human", "_reg")
    ) %>%
    transmute(
      coder_1 = "RegCheck",
      coder_2 = coder_human,
      comparison_type = "regcheck_human",
      journal,
      paper_id,
      dimension,
      agree = as.integer(deviation_decision_human == deviation_decision_reg)
    )

  pairwise_df <- bind_rows(
    hh_pairs %>%
      transmute(
        coder_1, coder_2, comparison_type, journal, paper_id, dimension, agree
      ),
    rh_pairs
  ) %>%
    mutate(
      coder_pair = paste(pmin(coder_1, coder_2), pmax(coder_1, coder_2), sep = "_")
    )

  # ----------------------------
  # random effects for cosine similarity (fixed SDs; optionally fixed draws)
  # ----------------------------
  if (is.null(random_effects)) {
    coder_pair_universe <- all_possible_coder_pairs(human_coders)

    random_effects <- list(
      paper_effects = rnorm(n_papers, 0, re_sds$paper) |>
        setNames(as.character(paper_ids)),
      coder_pair_effects = rnorm(length(coder_pair_universe), 0, re_sds$coder_pair) |>
        setNames(coder_pair_universe),
      dimension_effects = rnorm(length(dimensions), 0, re_sds$dimension) |>
        setNames(dimensions),
      journal_effects = rnorm(length(journals), 0, re_sds$journal) |>
        setNames(journals)
    )
  }

  # Apply cosine model (normal + residual + clamp), with BUG FIX on clamping
  pairwise_df <- pairwise_df %>%
    rowwise() %>%
    mutate(
      cosine_similarity =
        cosine_base_mean[[comparison_type]] +
        random_effects$paper_effects[[as.character(paper_id)]] +
        random_effects$coder_pair_effects[[coder_pair]] +
        random_effects$dimension_effects[[dimension]] +
        random_effects$journal_effects[[journal]] +
        rnorm(1, 0, re_sds$residual)
    ) %>%
    ungroup() %>%
    mutate(cosine_similarity = clamp01(cosine_similarity))

  # return everything you need for analysis + reusing effects
  list(
    df_raw = df_raw,
    pairwise_df = pairwise_df,
    pair_agreement = pair_agreement,
    random_effects = random_effects,
    settings = list(
      n_papers = n_papers,
      hh_agree_mean = hh_agree_mean,
      rc_agree_mean = rc_agree_mean,
      hh_agree_sd = hh_agree_sd,
      rc_agree_sd = rc_agree_sd,
      cosine_base_mean = cosine_base_mean,
      re_sds = re_sds
    )
  )
}



# 1) Create a baseline run to get random_effects draws
base <- simulate_regcheck_validation_data(n_papers = 200)

# 2) Reuse base$random_effects across scenarios
scenario_grid <- tidyr::expand_grid(
  hh = c(0.65, 0.75, 0.85),
  rc = c(0.70, 0.80, 0.90),
  n  = c(50, 100, 150, 200)
)

sims <- purrr::pmap(
  scenario_grid,
  function(hh, rc, n) {
    simulate_regcheck_validation_data(
      n_papers = n,
      hh_agree_mean = hh,
      rc_agree_mean = rc,
      random_effects = base$random_effects   # reuse draws
    )
  }
)


```




# RQ2: Deviation decision agreement

# RQ3: Hyperparameter performance



